### PR TITLE
saving dependent projects to a file

### PR DESCRIPTION
**Pull request by Felioh**

### CODE REVIEW

**Comment by Felioh** [comment]
This saves an extra file, which contains the modules that are dependent on changed modules.
This might be important in a ci pipeline to trigger tests on those modules

**Comment by avodonosov** [comment]
@Felioh, it's a some confusion on your part, it seems. The projects you are saving do not need to be tested. All modules affected , directly and indirectly, are already saved to a files.

**Comment by avodonosov** [comment]
For example, if subModuleX is changed in a project with the following structure:

```
- moduleA
  - subModuleX
  - subModuleY
- moduleB
- moduleC
```

the `mvn package -pl :moduleA,:subModuleX -am` will also rebuild unchnaged subModuleY because it is required for moduleA build.

Your change will save the subModuleY.

**Comment by Felioh** [comment]
@avodonosov we are using gitlab ci/cd and have different job for every module that needs to be tested. With my changes we can export the list as a variable and use that to schedule only those jobs that need to be tested.
I understand that this is not a common usecase, however I thought this might be relevant for others.

**Comment by avodonosov** [comment]
@Felioh, but why would you need to test the subModuleY?

Only subModuleX, which was changed directly, and the moduleA, depending on it and thus possibly affected, need to be tested. They are already listed in the file target/hashver-projects-to-build.

**Pull request closed without merging**
